default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  # database: rails-watch-list_development
  database: heroku_dbs_manager_development

test:
  <<: *default
  database: rails-watch-list_test
